version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.13.0
  environment:
  - ENV: prod
  - NODE_ENV: production

jobs:
  check-versions:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Show node version
          command: node --version
      - run:
          name: Show npm version
          command: npm --version
      - run:
          name: Show yarn version
          command: yarn --version
  install_dependencies:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: yarn --pure-lockfile
  build:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Build
        command: yarn build

workflows:
  version: 2
  pipeline:
    jobs:
      - check-versions
      - install_dependencies
      - build:
          requires:
            - install_dependencies