version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.13.0
  environment:
  - ENV: prod
  - NODE_ENV: production
  - CI: true
  - JEST_JUNIT_OUTPUT: ./test-results/jest/results.xml

jobs:
  check-versions:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Show node version
          command: node --version
      - run:
          name: Show npm version
          command: npm --version
      - run:
          name: Show yarn version
          command: yarn --version
  install_dependencies:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        name: Restore Yarn Package Cache
        keys:
          - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-{{ .Branch }}
          - yarn-packages-master
          - yarn-packages-
    - run:
        name: Install Dependencies
        command: yarn --pure-lockfile --production=false
    - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths:
          - node_modules/
    - persist_to_workspace:
        root: .
        paths:
          - node_modules/*
  build:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: yarn build
    - persist_to_workspace:
        root: .
        paths:
          - node_modules/*
          - build/*
          - firebase.json
          - .firebaserc
  create_artifact:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - store_artifacts:
        path: build
  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Test
        command: yarn test --ci --coverage --reporters=default --reporters=jest-junit
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: coverage
        prefix: coverage
  lint:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Lint
        command: yarn lint

  deploy:
    <<: *defaults
    steps:
    - attach_workspace:
        at: .
    - run:
        name: Deploy to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  version: 2
  pipeline:
    jobs:
      - check-versions
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint
            - test
            - install_dependencies
      - create_artifact:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - hold
            - build
          filters:
            branches:
              only: master