version: 2

defaults: &defaults
  docker:
  - image: circleci/node:10.13.0
  environment:
  - ENV: prod
  - NODE_ENV: production

jobs:
  check-versions:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Show node version
          command: node --version
      - run:
          name: Show npm version
          command: npm --version
      - run:
          name: Show yarn version
          command: yarn --version
  install_dependencies:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: Install Dependencies
        command: yarn --pure-lockfile
    - persist_to_workspace:
        root: .
        paths:
          - node_modules/*
  build:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: yarn build
  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: yarn test
  lint:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: Build
        command: yarn lint

workflows:
  version: 2
  pipeline:
    jobs:
      - check-versions
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - lint
            - test
            - install_dependencies